### ISSUE TITLE
Tag `v1.4.12` removed?

### ISSUE THREAD

**Issue by ZhongRuoyu** [mavlink/MAVSDK#1978] opened 2023-02-04 10:16 UTC
Hi! Homebrew contributor here. We noticed that tag `v1.4.12` was removed. Was that intended?

**Comment by julianoes** [comment] 2023-02-07 20:06
Sorry, I pushed it by mistake. It was a duplicate of v1.4.11.

**Comment by chenrui333** [comment] 2023-02-08 01:05
@julianoes thanks for confirming that was intended, any timeline plan for a new release any time soon (asking so that we don't have to downgrade the mavsdk, which is some painful process for homebrew side). Thanks a lot!

**Comment by julianoes** [comment] 2023-02-08 03:45
Ok, I'll try to make a release tomorrow to make this easier for you. Thanks!

**Comment by chenrui333** [comment] 2023-02-09 14:54
That would be much better.

**Comment by julianoes** [comment] 2023-02-10 00:37
I've released v1.4.12, hopefully that works for you.
https://github.com/mavlink/MAVSDK/releases/tag/v1.4.12

**Closed by julianoes** 2023-02-10 00:37 UTC

**Comment by ZhongRuoyu** [comment] 2023-02-10 00:58
Thanks @julianoes (and @chenrui333)!

**Comment by julianoes** [comment] 2023-02-10 01:00
And thank you for maintaining the homebrew updates!
