### ISSUE TITLE
MavlinkPassthrough support in language wrappers

### ISSUE THREAD

**Issue by david6096** [mavlink/MAVSDK#2161] opened 2023-10-20 06:47 UTC
I want to process custom mavlink message from android platform,but MavlinkPassthrough plugin not exported to mavsdkserver through protobuf rgpc.any scheduling for this?

**Comment by JonasVautherin** [comment] 2023-10-20 07:58
It is not scheduled. @divyanshupundir is using https://github.com/divyanshupundir/mavlink-kotlin in parallel to MAVSDK-Java, I think.

If you only want to do raw mavlink you can look directly into mavlink-kotlin, I would say.

**Comment by julianoes** [comment] 2024-05-20 04:27
This would be nice and is something I have planned to do. However, it's not exactly my day job, so if you want to accelerate it, consider [throwing something in the hat](https://github.com/sponsors/julianoes).

**Comment by julianoes** [comment] 2024-05-27 09:30
Duplicate of #1459 .

**Closed by julianoes** 2024-05-27 09:30 UTC
