### ISSUE TITLE
mavsdk::Gimbal::control() exception but mavsdk::Gimbal::subscribe_control() OK

### ISSUE THREAD

**Issue by dzywater** [mavlink/MAVSDK#1711] opened 2022-03-03 08:25 UTC
Call mavsdk::Gimbal::subscribe_control() OK.
Call mavsdk::Gimbal::control() exception: Unable to open 'pthread_once.c': File not found.

**Comment by JonasVautherin** [comment] 2022-03-03 09:44
Which version of MAVSDK are you using? On which platform? Are you able to write a minimal, runnable example that reproduces the bug so that someone can try to fix it?

**Comment by dzywater** [comment] 2022-03-03 15:46
V1.0.8，ubuntu20.04.
On Windows10, System::has_gimbal() returns false.

**Comment by julianoes** [comment] 2022-03-03 20:36
Can you provide the full compile or run output please? I have never seen this before.

**Comment by dzywater** [comment] 2022-03-04 03:24
![3](https://user-images.githubusercontent.com/22073470/156693404-3920c12b-dad2-4e39-a4dc-aa88490fa035.png)

**Comment by julianoes** [comment] 2022-03-06 21:10
@dzywater by the way, if you put ``` around your code it gets nicely formatted.

Thanks for sharing the example. I'll try to reproduce this.

**Comment by julianoes** [comment] 2022-03-06 22:03
I can't reproduce this with MAVSDK from the main branch or release 1.0.8.

If you could get a backtrace where it happens, that would be very helpful.
To get a backtrace, the easiest is to run it in gdb:

```gdb --args your_exe```

Then you type `run` and enter, and once it crashes you do `backtrace` and copy that here.

**Comment by julianoes** [comment] 2023-03-13 23:34
Closing as there was no follow up.

**Closed by julianoes** 2023-03-13 23:34 UTC
Labels: bug, windows
