### ISSUE TITLE
want to write example code of drone mission_raw

### ISSUE THREAD

**Issue by pwl24** [mavlink/MAVSDK#1970] opened 2023-01-30 01:58 UTC
Hi I would like to run the drone mission with the local position, I use the mission_row i got the unsupported error from it
i set the param as below,
mission_items = []
mission_items.append(MissionItem(0,
1,
16,
1,
1,
float('nan'),
float('nan'),
float('nan'),
float('nan'),
25,
25,
-25,
0))
I am running the simulation with jmavsim
or is there any mission_raw example code like mission , That will me helpful for me as well

**Comment by julianoes** [comment] 2023-01-30 03:27
Duplicate of https://github.com/mavlink/MAVSDK-Python/issues/549.

**Closed by julianoes** 2023-01-30 03:27 UTC
